### ISSUE TITLE
plant colors in sky islands and farm arrays being wrong

### ISSUE THREAD

**Issue by toastombee** [SchuhBaum/SBCameraScroll#12]
The colors of certain background plants in Farm Arrays and Sky Islands (and maybe other regions, though I haven't noticed anything yet) are broken and appear dead. As far as I can tell, you don't need to take any particular steps to recreate this bug other than turning the mod on. 

![image](https://github.com/SchuhBaum/SBCameraScroll/assets/171192281/5695bcd9-0b95-48e3-b75a-93a18ca18715)
![image](https://github.com/SchuhBaum/SBCameraScroll/assets/171192281/f61e7483-dfd8-42a9-8e28-d1dc2d3e9b1a)

**Comment by SchuhBaum** [comment]
Looks like shader issues. I'll see if I can fix this. Here is an image how it is supposed to look like (for reference):
![1](https://github.com/SchuhBaum/SBCameraScroll/assets/113112213/73093c48-ee19-4073-a57d-3b5935bbd233)

**Comment by SchuhBaum** [comment]
Small update:
I figured out what happens. There is additional color information for some objects added to the room background texture itself (see attached screenshot). Since they are merged the location changes and the shader does not find them anymore.
I still need to extend the shader to handle multiple such color informations at once, otherwise these objects change color when you move past the current screen borders.
![1](https://github.com/SchuhBaum/SBCameraScroll/assets/113112213/93d1c40f-daaf-49bb-aded-1068c92040ab)

**Comment by SchuhBaum** [comment]
Should be fixed in v2.8.3. I have not tested many rooms yet. If you still encounter this issue let me know.
