### ISSUE TITLE
Feature Suggestion/Request

### ISSUE THREAD

**Issue by GoobyMain** [SchuhBaum/SBCameraScroll#7]
This mod is a lifesaver for jolly coop in those big rooms with multiple screen transitions, but in my own single player playthrough I've noticed the screen scrolling feels a little jarring? Like the large rooms in the game no longer feel divided into many smaller rooms, which normally would each be their own sort of set piece? ( sorry I'm having trouble describing this, I sort of mean that the mod feels too smooth and maybe that contrasts too much with rain world's style )

I think it would be possible to add an option to make it so the camera centers on each screen, like the vanilla behavior, and then as you approach the edge of the screen connected to another the camera scrolls between the two rooms. So when playing the game, the big room would still feel divided into multiple screens, like vanilla behavior, but while you're in a small transition area on the border of two screens, you'd be able to see at least the terrain/enemies directly in front of you, instead of just being blind, and you wouldn't leave your teammates stranded on the last screen.

I think it might be a good way to keep the style of the level design from the base game while also using this mod, like a decent compromise between the two. At the same time, it might just be too jarring and not work at all, or just not worth the effort to implement.

**Comment by SchuhBaum** [comment]
Hm.... The question for me is how small is the transition area. Some comments:
-Vanilla camera positions already have overlap. You see a common area from both sides (the angle might be different). In this sense you always see enemies directly in front of you. (Vertically not so much but that is the 16:9 resolution more than anything.)
-Depending on the size of the area the camera might need to move quite fast in order to overtake the player. One goal is to move the camera as little and as predictable as possible. This is a problem that makes moving the camera in front of the player less good and one reason why that option is disabled by default. The camera only stays behind. (Context: There is an option to let the camera move past slugcat so that you can see further ahead.)
-Or you make it simply a transition that is triggered by the player. Then you have the same as in vanilla but the camera does not teleport. Not sure how much better this is. It is probably better for people who can't stand the vanilla transitions.
-There is vanilla camera option. This gives you the possibility to switch between a centered camera position and vanilla camera positions. In most cases you know that there is little to fear during camera transitions. In some spots or rooms it is the opposite and that functionality can come in handy. The transition when switching is smooth so it is a little bit of that but more manual.

I am not really sold on the idea. Maybe I am thinking too technically here.

**Comment by GoobyMain** [comment]
Cool, thanks for the insight!

I was hoping it would work out somehow or you'd have some clever way to make it work and still feel smooth, but I think you're right to be thinking the way you are above. Thanks for humoring the idea at least, I appreciate it!
